# Generated by Django 6.0.2 on 2026-03-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('areaofspecialization', models.CharField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
